name: serviceresult
description: A dart class to intermediate services reponses.
version: 0.0.1
author: Jilly Taboga <jillyhelli@gmail.om>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: